//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunPHP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunPHP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon appicon {
            get {
                object obj = ResourceManager.GetObject("appicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon appicon16 {
            get {
                object obj = ResourceManager.GetObject("appicon16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appimage {
            get {
                object obj = ResourceManager.GetObject("appimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to php.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %CurDir%\App\php\php.exe.
        /// </summary>
        internal static string AppPath {
            get {
                return ResourceManager.GetString("AppPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -f &quot;{0}&quot;{1}.
        /// </summary>
        internal static string Args {
            get {
                return ResourceManager.GetString("Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /C TITLE PHP &amp;&amp; CALL &quot;{0}&quot; -f &quot;{1}&quot;{2} &amp;&amp; ECHO. &amp;&amp; ECHO. &amp;&amp; PAUSE.
        /// </summary>
        internal static string ComArgs {
            get {
                return ResourceManager.GetString("ComArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %ComSpec%.
        /// </summary>
        internal static string ComSpec {
            get {
                return ResourceManager.GetString("ComSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %WinDir%\explorer.exe.
        /// </summary>
        internal static string ExplorerPath {
            get {
                return ResourceManager.GetString("ExplorerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Script (*.php)|*.php|All Files (*.*)|*.*.
        /// </summary>
        internal static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sha1sum.txt.
        /// </summary>
        internal static string HashFile {
            get {
                return ResourceManager.GetString("HashFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP not found. Do you want to download the newest verson now?.
        /// </summary>
        internal static string Msg_Ask_00 {
            get {
                return ResourceManager.GetString("Msg_Ask_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to search updates for PHP?.
        /// </summary>
        internal static string Msg_Ask_01 {
            get {
                return ResourceManager.GetString("Msg_Ask_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available. Do you want to download it now?.
        /// </summary>
        internal static string Msg_Ask_02 {
            get {
                return ResourceManager.GetString("Msg_Ask_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no connection available..
        /// </summary>
        internal static string Msg_Err_00 {
            get {
                return ResourceManager.GetString("Msg_Err_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates available..
        /// </summary>
        internal static string Msg_Hint_00 {
            get {
                return ResourceManager.GetString("Msg_Hint_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed!.
        /// </summary>
        internal static string Msg_Hint_01 {
            get {
                return ResourceManager.GetString("Msg_Hint_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled!.
        /// </summary>
        internal static string Msg_Hint_02 {
            get {
                return ResourceManager.GetString("Msg_Hint_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed!.
        /// </summary>
        internal static string Msg_Warn_00 {
            get {
                return ResourceManager.GetString("Msg_Warn_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///TITLE PHP
        ///CD /D &quot;{1}&quot;
        ///CALL &quot;{0}&quot; {2}
        ///ECHO.
        ///ECHO.
        ///PAUSE
        ///EXIT.
        /// </summary>
        internal static string ScriptDummy {
            get {
                return ResourceManager.GetString("ScriptDummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %DesktopDirectory%\{0}-{1}.cmd.
        /// </summary>
        internal static string ScriptPath {
            get {
                return ResourceManager.GetString("ScriptPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debug
        ///devel
        ///nts
        ///test.
        /// </summary>
        internal static string SearchBlacklist {
            get {
                return ResourceManager.GetString("SearchBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -x86.zip.
        /// </summary>
        internal static string SearchMatch {
            get {
                return ResourceManager.GetString("SearchMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://windows.php.net/downloads/releases.
        /// </summary>
        internal static string UpdateUrl {
            get {
                return ResourceManager.GetString("UpdateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Script Launcher.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
